services:
  - type: web
    name: feeding-futures-backend
    env: node
    region: oregon
    branch: main
    root: backend       # <-- change this to the folder with package.json
    buildCommand: "npm install"
    startCommand: "node server.js"
    instanceType: free
    healthCheckPath: "/"
    envVars:
      - key: FRONTEND_URL
        value: "https://feeding-futures-user.vercel.app"
      - key: MONGO_URI
        value: "mongodb+srv://nm4746_db_user:Na%4015082005@cluster0.18b8ybu.mongodb.net/"
